### ISSUE TITLE
Unnecessary code?

### ISSUE THREAD

**Issue by Maikon** [sarahyjja/ContactManager2#3]
Possibly a debugging statement? :-)

https://github.com/sarahyjja/ContactManager2/blob/c5bf5b4517a3ad79f18acc738de99bef973104d9/lib/contact_list.rb#L24

**Comment by sarahyjja** [comment]
What do you mean? 😅

**Comment by Maikon** [comment]
That line prints to the console the value of the `@list` variable. It does not return a value that is used elsewhere. Is that desirable at that point in the program? 🙂

**Comment by sarahyjja** [comment]
yeah I realised it this morning haha
they are gone :)

**Comment by Maikon** [comment]
Cool 🙂👍
